### POST 생성
POST http://localhost:8080/api/v1/post
Content-Type: application/json

{
  "member_id": "test-id",
  "content" : "TEST 글을 작성해봅니다.",
  "photos": ["https://avatars.githubusercontent.com/u/46712693?v=4"]
}

### POST 수정
@id = variable value
PUT http://localhost:8080/api/v1/post/{{id}}
Content-Type: application/json

{
  "content" : "TEST 글을 수정해봅니다.",
  "photos": ["https://avatars.githubusercontent.com/u/46712693?v=4"]
}

### POST 삭제
DELETE http://localhost:8080/api/v1/post/{{id}}

### POST 조회
GET http://localhost:8080/api/v1/post/{{id}}?memberId=test-id1